status is-interactive; or exit 0

alias kb="kubectl"
alias istio="istioctl"
alias mk="minikube"
alias dc="docker-compose"
alias tf="terraform"
alias vi="nvim"
alias pm="pnpm"
alias px="pnpx"
alias tpe="telepresence"
alias docker="podman"
alias gci="cz"
alias tg="terragrunt"
alias dotfiles="chezmoi"
alias ll="eza --color=always --long --git --icons=always --no-user"
alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"
alias cat="bat --paging never --style=changes --theme base16"
alias less="bat --paging always --style=changes --theme base16"
alias top="btop"
alias todo="togo"

alias assume="source (brew --prefix)/bin/assume.fish"
