aliases: {}
cheatsh:
    enabled: true
    topics:
      golang: "go"
    baseurl: https://cheat.sh
    cacheenabled: true
    cacheduration: 168
    cachedir: /Users/danielbooth/.cache/how/cheatsh
    defaultoptions: T
display:
    usebat: true
    color: auto
    linenumbers: true
    pager: auto
fzf:
    enabled: true
    extraflags: --height 40% --border --preview-window=right:60%
guide_paths:
    - /Users/danielbooth/.config/how/guides
version: "1.0"
