[settings]
lockfile = true
idiomatic_version_file_enable_tools = ["terraform", "opentofu", "node", "go", "python"]

[tools]
awscli = { version = "latest", symlink_bins = true }
go = "latest"
helm = "latest"
helmfile = "latest"
krew = "latest"
kubectl = "latest"
minikube = "latest"
node = "latest"
pipx = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"
vcluster = "latest"
