dlv = github.com/go-delve/delve/cmd/dlv
godoc-mcp = github.com/mrjoshuak/godoc-mcp
goimports = golang.org/x/tools/cmd/goimports
gopls = golang.org/x/tools/gopls
staticcheck = honnef.co/go/tools/cmd/staticcheck
swag = github.com/swaggo/swag/cmd/swag
viscosity-cli = github.com/danielbooth-cloud/viscosity-cli
yatto = github.com/handlebargh/yatto
